# Generated by Django 5.0.7 on 2024-07-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_appointment',
            old_name='booked',
            new_name='user_booked',
        ),
    ]
