# Generated by Django 5.0.7 on 2024-07-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_booked_add_appointment_user_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_slote',
            old_name='user_booked',
            new_name='booked',
        ),
    ]
