# Generated by Django 5.0.7 on 2024-07-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_booked_booking_slote_user_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_appointment',
            name='user_booked',
        ),
    ]
