# Generated by Django 5.0.7 on 2024-07-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_add_appointment_user_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_appointment',
            name='user_booked',
            field=models.BooleanField(null=True),
        ),
    ]
