# Generated by Django 5.0.7 on 2024-07-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_appointment_user_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_appointment',
            name='user_booked',
            field=models.BooleanField(default=False),
        ),
    ]
