# Generated by Django 5.0.7 on 2024-07-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_slote_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_slote',
            name='booked_date',
        ),
    ]
