# Generated by Django 5.0.7 on 2024-07-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_add_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_feedbacks',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
