# Generated by Django 5.0.7 on 2024-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_add_feedbacks_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaints',
            name='admin_replay',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
