# Generated by Django 5.0.7 on 2024-08-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_add_complaints_admin_replay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_complaints',
            old_name='admin_replay',
            new_name='admin_reply',
        ),
    ]
