# Generated by Django 5.0.7 on 2024-08-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_admin_replay_add_complaints_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_complaints',
            name='reply_date',
            field=models.DateTimeField(null=True),
        ),
    ]
