# Generated by Django 5.0.7 on 2024-08-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_add_complaints_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_complaints',
            name='admin_reply',
            field=models.CharField(default='pending', max_length=500),
        ),
    ]
